# @2
# GHI CHÚ
# I) File này dùng để tổng hợp, phân loại chi phí. Sau đó đưa dữ liệu vào bảng TH_CP trong CSDL CP_KD
# II) Sử dụng dữ liệu từ sổ cái 6421, 6422 đã được xử lý ở file preprocess

In [18]:
import pandas as pd
import numpy as np

In [14]:
#TK6421

In [2]:
TK6421_20 = pd.read_csv('D://THUCTAP//data_da_xuly//6421_20.csv', encoding='utf-16', sep='\t')
TK6421_21 = pd.read_csv('D://THUCTAP//data_da_xuly//6421_21.csv', encoding='utf-16', sep='\t')
TK6421_22 = pd.read_csv('D://THUCTAP//data_da_xuly//6421_22.csv', encoding='utf-16', sep='\t')

In [15]:
#TK6422

In [3]:
TK6422_20 = pd.read_csv('D://THUCTAP//data_da_xuly//6422_20.csv', encoding='utf-16', sep='\t')
TK6422_21 = pd.read_csv('D://THUCTAP//data_da_xuly//6422_21.csv', encoding='utf-16', sep='\t')
TK6422_22 = pd.read_csv('D://THUCTAP//data_da_xuly//6422_22.csv', encoding='utf-16', sep='\t')

In [16]:
#gộp 6421

In [4]:
result1 = pd.concat([TK6421_20, TK6421_21, TK6421_22], ignore_index=True)
result1['Loại chi phí']='Chi phí bán hàng'
result1

,Ngay_chung_tu,So_chung_tu,Dien_giai,Phat_sinh,Loại chi phí
0,2020-02-01,PC00053,Chi thanh toán tiền mua dầu DO,6229636,Chi phí bán hàng
1,2020-02-04,PC00056,Chi thanh toán tiền mua dầu DO,912227,Chi phí bán hàng
2,2020-02-29,NVK065,Mua dầu DO,10238328,Chi phí bán hàng
3,2020-03-13,NVK079,Mua nợ dầu DO,1068600,Chi phí bán hàng
4,2020-03-15,NVK080,Mua nợ dầu DO,3493500,Chi phí bán hàng
...,...,...,...,...,...
138,2022-12-31,NVK3024,Mua dầu DO,5427391,Chi phí bán hàng
139,2022-12-31,NVK3514,Phân bổ lương năm 2022,1125899243,Chi phí bán hàng
140,2022-12-31,NVK3536,Phân bổ chi phí trích trước,126000000,Chi phí bán hàng
141,2022-12-31,NVK3537,Trích khấu hao TSCĐ,187773878,Chi phí bán hàng
142,2022-12-31,PC22_757,"Chi thanh toán tiền lương, ăn ca tháng 12",4380000,Chi phí bán hàng

In [17]:
#gộp 6422

In [5]:
result2 = pd.concat([TK6422_20, TK6422_21, TK6422_22], ignore_index=True)
result2['Loại chi phí']='Chi phí QLDN'
result2

,Ngay_chung_tu,So_chung_tu,Dien_giai,Phat_sinh,Loại chi phí
0,2020-01-05,PC00008,Chi thanh toán cước DV viễn thông,72146,Chi phí QLDN
1,2020-01-05,PC00009,Chi thanh toán cước DV viễn thông,177990,Chi phí QLDN
2,2020-01-07,UNC011,Phí chuyển tiền,786761,Chi phí QLDN
3,2020-01-07,UNC012,Phí chuyển tiền,121880,Chi phí QLDN
4,2020-01-08,UNC019,Phí,9900,Chi phí QLDN
...,...,...,...,...,...
1467,2022-12-31,NVK3513,BHXH phải nộp,16796613,Chi phí QLDN
1468,2022-12-31,NVK3513,BHXH phải nộp,1682936,Chi phí QLDN
1469,2022-12-31,NVK3514,Phân bổ lương năm 2022,157333400,Chi phí QLDN
1470,2022-12-31,NVK3536,Phân bổ chi phí trích trước,14982879,Chi phí QLDN
1471,2022-12-31,NVK3537,Trích khấu hao TSCĐ,111460601,Chi phí QLDN

In [ ]:
#gộp 6421 và 6422

In [6]:
result = pd.concat([result1, result2], ignore_index=True)

In [7]:
result

,Ngay_chung_tu,So_chung_tu,Dien_giai,Phat_sinh,Loại chi phí
0,2020-02-01,PC00053,Chi thanh toán tiền mua dầu DO,6229636,Chi phí bán hàng
1,2020-02-04,PC00056,Chi thanh toán tiền mua dầu DO,912227,Chi phí bán hàng
2,2020-02-29,NVK065,Mua dầu DO,10238328,Chi phí bán hàng
3,2020-03-13,NVK079,Mua nợ dầu DO,1068600,Chi phí bán hàng
4,2020-03-15,NVK080,Mua nợ dầu DO,3493500,Chi phí bán hàng
...,...,...,...,...,...
1610,2022-12-31,NVK3513,BHXH phải nộp,16796613,Chi phí QLDN
1611,2022-12-31,NVK3513,BHXH phải nộp,1682936,Chi phí QLDN
1612,2022-12-31,NVK3514,Phân bổ lương năm 2022,157333400,Chi phí QLDN
1613,2022-12-31,NVK3536,Phân bổ chi phí trích trước,14982879,Chi phí QLDN
1614,2022-12-31,NVK3537,Trích khấu hao TSCĐ,111460601,Chi phí QLDN

In [8]:
result

,Ngay_chung_tu,So_chung_tu,Dien_giai,Phat_sinh,Loại chi phí
0,2020-02-01,PC00053,Chi thanh toán tiền mua dầu DO,6229636,Chi phí bán hàng
1,2020-02-04,PC00056,Chi thanh toán tiền mua dầu DO,912227,Chi phí bán hàng
2,2020-02-29,NVK065,Mua dầu DO,10238328,Chi phí bán hàng
3,2020-03-13,NVK079,Mua nợ dầu DO,1068600,Chi phí bán hàng
4,2020-03-15,NVK080,Mua nợ dầu DO,3493500,Chi phí bán hàng
...,...,...,...,...,...
1610,2022-12-31,NVK3513,BHXH phải nộp,16796613,Chi phí QLDN
1611,2022-12-31,NVK3513,BHXH phải nộp,1682936,Chi phí QLDN
1612,2022-12-31,NVK3514,Phân bổ lương năm 2022,157333400,Chi phí QLDN
1613,2022-12-31,NVK3536,Phân bổ chi phí trích trước,14982879,Chi phí QLDN
1614,2022-12-31,NVK3537,Trích khấu hao TSCĐ,111460601,Chi phí QLDN

In [9]:
def replace_dien_giai(value):
    if 'lương' in value:
        return 'Chi phí nhân sự'
    elif 'xăng' in value or 'dầu' in value:
        return 'Chi phí xăng dầu'
    elif 'đường bộ' in value:
        return 'chi phí đường bộ'
    elif 'khấu hao' in value and 'TSCĐ' in value:
        return 'Chi phí khấu hao TSCĐ'
    else:
        return value

In [11]:
result['Dien_giai'] = result['Dien_giai'].apply(replace_dien_giai)

In [13]:
result

,Ngay_chung_tu,So_chung_tu,Dien_giai,Phat_sinh,Loại chi phí
0,2020-02-01,PC00053,Chi phí xăng dầu,6229636,Chi phí bán hàng
1,2020-02-04,PC00056,Chi phí xăng dầu,912227,Chi phí bán hàng
2,2020-02-29,NVK065,Chi phí xăng dầu,10238328,Chi phí bán hàng
3,2020-03-13,NVK079,Chi phí xăng dầu,1068600,Chi phí bán hàng
4,2020-03-15,NVK080,Chi phí xăng dầu,3493500,Chi phí bán hàng
...,...,...,...,...,...
1610,2022-12-31,NVK3513,BHXH phải nộp,16796613,Chi phí QLDN
1611,2022-12-31,NVK3513,BHXH phải nộp,1682936,Chi phí QLDN
1612,2022-12-31,NVK3514,Chi phí nhân sự,157333400,Chi phí QLDN
1613,2022-12-31,NVK3536,Phân bổ chi phí trích trước,14982879,Chi phí QLDN
1614,2022-12-31,NVK3537,Chi phí khấu hao TSCĐ,111460601,Chi phí QLDN

In [9]:
result.to_csv('D://THUCTAP//data_da_xuly//TH_CP.csv', index=False,  encoding='utf-16', sep='\t')